### PR TITLE
fixes typo from en dash to hyphen

### PR DESCRIPTION
**Pull request by jajajaime**

### CODE REVIEW

**Comment by jajajaime** [comment]
@meker12 why was this marked as won't fix? The documentation for this has copy and paste instructions, and when you do that, you get errors because of wrong characters.

**Comment by meker12** [comment]
@jajajaime  My mistake -- I didn't register that it was a code sample that you were fixing. I'll merge this change to our internal repository to update the topic on ExL.  Thanks for the report.

**Comment by hguthrie** [comment]
@jajajaime Can you please add a description and sign the CLA so we can process this?

**Comment by jajajaime** [comment]
Closing and opening for the CLA process.

**Comment by meker12** [comment]
PR ported to internal repo. Update published to ExL: https://experienceleague.adobe.com/docs/commerce-merchant-services/live-search/onboard/install.html?lang=en

**Pull request closed without merging**
