### PR TITLE
Update boundaries-limits.md

### PR DESCRIPTION
**Pull request by shiftedreality**
## Purpose of the pull request

This pull request (PR) ...

## Affected pages

- ...

### CODE REVIEW

**Comment by erikmarr** [comment]
@devops-devdocs import the pr

**Comment by devops-devdocs** [comment]
@devops-devdocs imported this pull request

**Comment by erikmarr** [comment]
Imported to internal repo: https://git.corp.adobe.com/AdobeDocs/commerce-merchant-services.en/pull/649

**Comment by dshevtsov** [comment]
@erikmarr I'm reopening this PR to allow it for automerging when the internally merged commit gets to this mirror via repository syncing service.

**Comment by devops-devdocs** [comment]
Something went wrong

**Pull request merged**
